# Generated by Django 4.1.5 on 2023-01-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_funcionario_user'),
        ('documentos', '0002_documentos_pertence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='pertence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario'),
            preserve_default=False,
        ),
    ]
