# Generated by Django 4.1.5 on 2023-02-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_funcionario_empresa'),
        ('documentos', '0005_rename_documentos_documento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documento',
            new_name='Documentos',
        ),
    ]
